### ISSUE TITLE
docker swarm reading adguard_password from secret

### ISSUE THREAD

**Issue by mvadu** [ebrianne/adguard-exporter#19]
readme example given is assigning the secret file to an environment variable. I don't see anywhere in the code where its checked to see if `config.adguard_password` is a file (which will be in this example) and read from it. As of now code is simply passing `/run/secrets/my-adguard-pass` as password, which obviously fails. 

```yaml
 secrets:
      - my-adguard-pass
    environment:
      - adguard_password=/run/secrets/my-adguard-pass
```

ref: https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images

> Docker secrets do not set environment variables directly. This was a conscious decision, because environment variables can unintentionally be leaked between containers (for instance, if you use --link).
